### ISSUE TITLE
Unable to access class files [Lotame Jar]

### ISSUE THREAD

**Issue by ghost** [Lotame/cc-android-sdk#3]
I've been able to successfully build the jar file and add it to a sample Android Studio project. However, I cannot access any of the jars' class files.

Here are the following steps I took:

1) Added the lotame jar to the projects' app/libs folder.
2) Added the jar as a library
3) Attempted to call CrowdControl.enableDebug(true) 

Here is a link to the sample project: 

https://github.com/Jibar/LotameTest

I've followed the same steps with another jar file (YoutubeAndroidPlayer), and was able to successfully access the jar class files for that library.

**Comment by dandalf** [comment]
I don't have access to the link you posted, but I am seeing the issue you are talking about by following your steps. I must have changed something with the jar creation while enabling maven/jcenter support. 
I recommend using maven dependencies until I figure out what went wrong. Add this line to your dependencies:
`compile 'com.lotame:cc-android-sdk:2.3.0.2'`

**Comment by dandalf** [comment]
@Jibar I've updated the project to work as you're expecting, but you will need to use `./gradlew clean jarRelease` instead of `./gradlew clean jar`.  I updated the README to reflect these changes.  Thank you for reporting the issue!
