### ISSUE TITLE
error: cannot find symbol method onPrepareOptionsPanel(View,Menu)

### ISSUE THREAD

**Issue by aryono-mcm** [Lotame/cc-android-sdk#4]
After adding 
compile 'com.lotame:cc-android-sdk:2.3.0.2'
to my gradle.build, this error show up:
error: cannot find symbol method onPrepareOptionsPanel(View,Menu)

I create new project just to make sure, and still, the same error occur.
[source.zip](https://github.com/Lotame/cc-android-sdk/files/1169280/source.zip)

If you need more details, please let me know

**Comment by ghost** [comment]
Same issue,

I can't build project after adding library as a gradle dependencies from jcenter.
No problem when i add the library as a module of my project.
I don't know why but all method issued from support library cause the error : "cannot find symbol method".
For example : 
ContextCompat.getDrawable(...)
ContextCompat.getColor(...)

and "cannot find symbol class PageTransformer"
For example :
ViewPager.PageTransformer

Thanks

**Comment by dandalf** [comment]
@aryono-mcm do you mean to use onPrepareOptionsMenu? I don't see onPrepareOptionsPanel in the appcompat libraries

**Comment by dandalf** [comment]
@aryono-mcm @laruedavid Can you try the new version with `compile 'com.lotame:cc-android-sdk:2.3.0.4'`?
The only change is that it is no longer including the lib folder, which was causing these errors.

**Comment by aryono-mcm** [comment]
Yes, the new version solved this.
Now I can build my project.
thank you @dandalf
